version: '3'

services:
  multiple-tenant-solution-server: 
    container_name: multiple-tenant-solution-server
    hostname: multiple-tenant-solution-server
    restart: always
    build: 
      context: .
      dockerfile: ./multiple-tenant-solution/Dockerfile
    ports: 
      - '6666:6666'
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    environment:
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - POSTGRES_DB=$POSTGRES_DB
    ports:
        - '5432:5432'
    volumes:
        - ~/.docker-volumns/multiple-tenant-solution-db:/var/lib/postgresql/data

        