// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using multiple_tenant_storage.Context;

#nullable disable

namespace multiple_tenant_storage.Migrations
{
    [DbContext(typeof(TenantContext))]
    [Migration("20230720024233_init table ")]
    partial class inittable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app_main_schema")
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("multiple_tenant_storage.Entities.Tenants", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConnectionPwd")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("connection_pwd");

                    b.Property<string>("ConnectionUserId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("connection_user_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("create_user");

                    b.Property<bool?>("IsEnable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("number");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("update_user");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("tenants", "app_tenant_schema");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ConnectionPwd = "admin",
                            ConnectionUserId = "admin",
                            CreateDate = new DateTime(2023, 7, 20, 2, 42, 32, 957, DateTimeKind.Utc).AddTicks(6313),
                            CreateUser = "admin",
                            IsEnable = true,
                            Name = "管理員",
                            Number = "admin",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            ConnectionPwd = "CompanyA",
                            ConnectionUserId = "CompanyA",
                            CreateDate = new DateTime(2023, 7, 20, 2, 42, 32, 957, DateTimeKind.Utc).AddTicks(6319),
                            CreateUser = "admin",
                            IsEnable = true,
                            Name = "A公司",
                            Number = "CompanyA",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3L,
                            ConnectionPwd = "CompanyB",
                            ConnectionUserId = "CompanyB",
                            CreateDate = new DateTime(2023, 7, 20, 2, 42, 32, 957, DateTimeKind.Utc).AddTicks(6321),
                            CreateUser = "admin",
                            IsEnable = true,
                            Name = "B公司",
                            Number = "CompanyB",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
